name = "rgb-bot"
main = "src/index.js"
compatibility_date = "2025-01-01"

[[kv_namespaces]]
binding = "KV"
id = "9b97fb1e48274d629462f53498541224"

[vars]
REDIRECT_URI = "https://rgb-bot.YOUR-SUBDOMAIN.workers.dev/api/callback"
WORKER_URL = "https://rgb-bot.YOUR-SUBDOMAIN.workers.dev"

[triggers]
crons = ["0 */3 * * *"]
